/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ChartOptions } from "chart.js";
export { ChartOptions } from "chart.js";
export namespace Components {
    interface CollateralCompositionBarChart {
        "chartOptions": ChartOptions<'bar'>;
        "height": string;
        "sx": string;
        "token": string;
        "width": string;
    }
    interface DelegateVotingPowerChart {
        "chartOptions": ChartOptions<'line'>;
        "height": string;
        "sx": string;
        "token": string;
        "width": string;
    }
}
declare global {
    interface HTMLCollateralCompositionBarChartElement extends Components.CollateralCompositionBarChart, HTMLStencilElement {
    }
    var HTMLCollateralCompositionBarChartElement: {
        prototype: HTMLCollateralCompositionBarChartElement;
        new (): HTMLCollateralCompositionBarChartElement;
    };
    interface HTMLDelegateVotingPowerChartElement extends Components.DelegateVotingPowerChart, HTMLStencilElement {
    }
    var HTMLDelegateVotingPowerChartElement: {
        prototype: HTMLDelegateVotingPowerChartElement;
        new (): HTMLDelegateVotingPowerChartElement;
    };
    interface HTMLElementTagNameMap {
        "collateral-composition-bar-chart": HTMLCollateralCompositionBarChartElement;
        "delegate-voting-power-chart": HTMLDelegateVotingPowerChartElement;
    }
}
declare namespace LocalJSX {
    interface CollateralCompositionBarChart {
        "chartOptions"?: ChartOptions<'bar'>;
        "height"?: string;
        "sx"?: string;
        "token"?: string;
        "width"?: string;
    }
    interface DelegateVotingPowerChart {
        "chartOptions"?: ChartOptions<'line'>;
        "height"?: string;
        "sx"?: string;
        "token"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "collateral-composition-bar-chart": CollateralCompositionBarChart;
        "delegate-voting-power-chart": DelegateVotingPowerChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "collateral-composition-bar-chart": LocalJSX.CollateralCompositionBarChart & JSXBase.HTMLAttributes<HTMLCollateralCompositionBarChartElement>;
            "delegate-voting-power-chart": LocalJSX.DelegateVotingPowerChart & JSXBase.HTMLAttributes<HTMLDelegateVotingPowerChartElement>;
        }
    }
}
