/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ChartOptions } from "chart.js";
export { ChartOptions } from "chart.js";
export namespace Components {
    interface DelegateVotingPowerChart {
        "chartOptions": ChartOptions<'line'>;
        "height": string;
        "sx": string;
        "token": string;
        "width": string;
    }
}
declare global {
    interface HTMLDelegateVotingPowerChartElement extends Components.DelegateVotingPowerChart, HTMLStencilElement {
    }
    var HTMLDelegateVotingPowerChartElement: {
        prototype: HTMLDelegateVotingPowerChartElement;
        new (): HTMLDelegateVotingPowerChartElement;
    };
    interface HTMLElementTagNameMap {
        "delegate-voting-power-chart": HTMLDelegateVotingPowerChartElement;
    }
}
declare namespace LocalJSX {
    interface DelegateVotingPowerChart {
        "chartOptions"?: ChartOptions<'line'>;
        "height"?: string;
        "sx"?: string;
        "token"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "delegate-voting-power-chart": DelegateVotingPowerChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "delegate-voting-power-chart": LocalJSX.DelegateVotingPowerChart & JSXBase.HTMLAttributes<HTMLDelegateVotingPowerChartElement>;
        }
    }
}
